baseurl = "https://vpsaddict.com"
title = "Jonathan Mainguy - vpsaddict.com"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#disqusShortname = "yourdiscussshortname"

[params]
    author = "Jonathan Mainguy"
    info = "Linux Systems Reliability Engineer and Luthier"
    description = "Jonathan Mainguy's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/images/Profile.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Jonathan Mainguy appreciates you."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jmainguy/"
[[params.social]]
    name = "Jmainguy.com"
    icon = "fas fa-blog fa-2x"
    weight = 2
    url = "https://jmainguy.com/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/standouthost/"
[[params.social]]
    name = "Standouthost.com"
    icon = "fas fa-blog fa-2x"
    weight = 4
    url = "https://standouthost.com/"
[[params.social]]
    name = "Soh.re"
    icon = "fas fa-terminal fa-2x"
    weight = 5
    url = "https://soh.re/"
[[params.social]]
    name = "Brandyourself"
    icon = "fas fa-male fa-2x"
    weight = 6
    url = "https://jonathanmainguy.brandyourself.com/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 7
    url = "https://www.linkedin.com/in/jonathan-mainguy-76174a54/"

# Menu links
#[[menu.main]]
#    name = "Blog"
#    weight = 1
#    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
